apiVersion: v1
kind: Pod
metadata:
  name: pod-for-odf
  labels:
    app: httpd
  namespace: test
spec:
  initContainers:
    - name: init
      image: registry.redhat.io/rhel7-minimal
      command:
        - /bin/sh
        - -c
        - echo Hello World! > /tmp/index.html
      volumeMounts:
        - name: odf-vol
          mountPath: /tmp
  containers:
    - name: httpd
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: odf-vol
          mountPath: /var/www/html
  volumes:
    - name: odf-vol
      persistentVolumeClaim:  
        claimName: odf-vol-claim        
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odf-vol-claim
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1Gi
