apiVersion: v1
kind: Pod
metadata:
  name: new-pod-odf
  labels:
    app: httpd
  namespace: test
spec:
  containers:
    - name: new-httpd
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: new-volume
          mountPath: /var/www/html
  volumes:
    - name: new-volume
      persistentVolumeClaim:  
        claimName: odf-vol-claim  
